# Generated by Django 5.0.2 on 2024-03-10 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'career',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='IncruitJobMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('incruit_job', models.TextField()),
                ('saramin_job', models.TextField()),
            ],
            options={
                'db_table': 'incruit_job_mapping',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'job_category',
            },
        ),
        migrations.CreateModel(
            name='JobkoreaEduMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jk_edu', models.TextField()),
                ('si_edu', models.TextField()),
            ],
            options={
                'db_table': 'jobkorea_edu_mapping',
            },
        ),
        migrations.CreateModel(
            name='JobkoreaJobMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jobkorea_job', models.TextField()),
                ('saramin_job', models.TextField()),
            ],
            options={
                'db_table': 'jobkorea_job_mapping',
            },
        ),
        migrations.CreateModel(
            name='Region1st',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'region_1st',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'work_type',
            },
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=90)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_details', to='posting.job')),
                ('job_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_details', to='posting.jobcategory')),
            ],
            options={
                'db_table': 'job_detail',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=90)),
                ('post_name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('created_at', models.DateField()),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posting.education')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posting.job')),
            ],
            options={
                'db_table': 'job_posting',
            },
        ),
        migrations.CreateModel(
            name='JobPostingCareer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posting.career')),
                ('job_posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posting.jobposting')),
            ],
            options={
                'db_table': 'job_posting_career',
            },
        ),
        migrations.CreateModel(
            name='Region2nd',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
                ('region_1st', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posting.region1st')),
            ],
            options={
                'db_table': 'region_2nd',
            },
        ),
        migrations.CreateModel(
            name='RegionPostingRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_posting_relations', to='posting.job')),
                ('region_2nd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_posting_relations', to='posting.region2nd')),
            ],
            options={
                'db_table': 'region_posting_relation',
            },
        ),
        migrations.CreateModel(
            name='JobPostingWorkType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_types', to='posting.jobposting')),
                ('work_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_types', to='posting.worktype')),
            ],
            options={
                'db_table': 'job_posting_work_type',
            },
        ),
    ]
