# Generated by Django 5.0.2 on 2024-03-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'career',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'education',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncruitJobMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('incruit_job', models.TextField()),
                ('saramin_job', models.TextField()),
            ],
            options={
                'db_table': 'incruit_job_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'job_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'job_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=90)),
                ('post_name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('created_at', models.DateField()),
            ],
            options={
                'db_table': 'job_posting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobPostingCareer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'job_posting_career',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobPostingWorkType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'job_posting_work_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region1st',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'region_1st',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region2nd',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'region_2nd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionPostingRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'region_posting_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'work_type',
                'managed': False,
            },
        ),
    ]
