# Generated by Django 5.0.2 on 2024-03-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobKoreaRegionMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jk_region', models.TextField()),
                ('si_region', models.TextField()),
            ],
            options={
                'db_table': 'jobkorea_region_mapping',
            },
        ),
    ]
