# Generated by Django 5.0.2 on 2024-03-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobkoreaJobMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jobkorea_job', models.TextField()),
                ('saramin_job', models.TextField()),
            ],
        ),
    ]
