# Generated by Django 5.0.2 on 2024-03-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_jobkoreajobmapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobkoreajobmapping',
            options={'managed': False},
        ),
    ]
