# Generated by Django 5.0.2 on 2024-03-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_jobkorearegionmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncruitEducationMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ic_edu', models.TextField()),
                ('si_edu', models.TextField()),
            ],
            options={
                'db_table': 'incruit_education_mapping',
            },
        ),
        migrations.CreateModel(
            name='IncruitJobDetailMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ic_job_detail', models.TextField()),
                ('si_job_detail', models.TextField()),
            ],
            options={
                'db_table': 'incruit_job_detail_mapping',
            },
        ),
        migrations.CreateModel(
            name='IncruitRegionMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ic_region', models.TextField()),
                ('si_region', models.TextField()),
            ],
            options={
                'db_table': 'incruit_region_mapping',
            },
        ),
        migrations.CreateModel(
            name='IncruitWorkTypeMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ic_work_type', models.TextField()),
                ('si_work_type', models.TextField()),
            ],
            options={
                'db_table': 'incruit_work_type_mapping',
            },
        ),
    ]
