# Generated by Django 5.0.2 on 2024-03-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_alter_jobkoreajobmapping_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobkoreaEduMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jk_edu', models.TextField()),
                ('si_edu', models.TextField()),
            ],
            options={
                'db_table': 'jobkorea_edu_mapping',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='jobkoreajobmapping',
            table='jobkorea_job_mapping',
        ),
    ]
