# Generated by Django 5.0.2 on 2024-03-18 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_alter_incruitjobdetailmapping_si_job_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='job',
        ),
        migrations.CreateModel(
            name='JobDetailPostingRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_detail_relation', to='posting.jobdetail')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_detail_relation', to='posting.jobposting')),
            ],
            options={
                'db_table': 'job_detail_posting_relation',
            },
        ),
    ]
