"""empty message

Revision ID: 3574da9911c5
Revises: 21b1ae0f0059
Create Date: 2024-02-05 15:44:19.844352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3574da9911c5'
down_revision = '21b1ae0f0059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('company_name', sa.String(length=20), nullable=False),
    sa.Column('post_name', sa.String(length=255), nullable=False),
    sa.Column('career', sa.String(length=20), nullable=True),
    sa.Column('education', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('job_type', sa.String(length=20), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('company_name', 'post_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
