"""empty message

Revision ID: d1240a70a3ff
Revises: 54553e09289b
Create Date: 2024-02-18 02:12:21.424530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1240a70a3ff'
down_revision = '54553e09289b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_2nd_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_post_region_1st_id_region_2nd', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_post_region_2nd_id_region_2nd'), 'region_2nd', ['region_2nd_id'], ['id'])
        batch_op.drop_column('region_1st_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_1st_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_post_region_2nd_id_region_2nd'), type_='foreignkey')
        batch_op.create_foreign_key('fk_post_region_1st_id_region_2nd', 'region_2nd', ['region_1st_id'], ['id'])
        batch_op.drop_column('region_2nd_id')

    # ### end Alembic commands ###
