"""empty message

Revision ID: 54553e09289b
Revises: 
Create Date: 2024-02-18 02:11:32.764561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54553e09289b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_region_1st_id_region_1st', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_post_region_1st_id_region_2nd'), 'region_2nd', ['region_1st_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_region_1st_id_region_2nd'), type_='foreignkey')
        batch_op.create_foreign_key('fk_post_region_1st_id_region_1st', 'region_1st', ['region_1st_id'], ['id'])

    # ### end Alembic commands ###
