# Generated by Django 5.0.2 on 2024-03-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_incruiteducationmapping_incruitjobdetailmapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incruitjobdetailmapping',
            name='si_job_detail',
            field=models.TextField(null=True),
        ),
    ]
