# Generated by Django 5.0.2 on 2024-03-18 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_alter_regionpostingrelation_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionpostingrelation',
            name='job',
        ),
        migrations.AddField(
            model_name='regionpostingrelation',
            name='job_posting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_posting_relations', to='posting.jobposting'),
        ),
    ]
